# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53db96677c1b3f341e7c799eb3480ffa009d7b7357c196a3d4a98d60a4eeddf84b2c8e195e3c9d3403b37f37ef32377102b40cc6e7d56dac1beeb94e4c74f6ef

test:
  secret_key_base: cb639d31a33d350493a8b44aa4a040917f9fff8ffd8d8014441a5ccd455632fa36df9da95ab8f1292abdd4b280e2447df4b798f1566476450af8469d354d2a23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
